/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ValidarCampos;
import Model.BancoDadosFichas;
import Model.ConexaoBanco;

import Model.Ficha;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Dhii
 */
public class CriaFicha extends javax.swing.JFrame {

    /**
     * Creates new form CriaFicha
     */
    ValidarCampos sv = new ValidarCampos();
    BancoDadosFichas bd = new BancoDadosFichas();
    
    
    public CriaFicha() {
        initComponents();
        DefaultTableModel df = (DefaultTableModel)jtFichas.getModel();
        jtFichas.setRowSorter(new TableRowSorter(df));
        ReadLista();
         
    }
    public void ReadLista(){
         DefaultTableModel df = (DefaultTableModel)jtFichas.getModel();
         df.setNumRows(0);
         for(Ficha f : BancoDadosFichas.ListaFichas()){
             
             df.addRow(new Object[]{f.getId(),f.getNome(),f.getTipoFicha(),f.getPv(),f.getCa(),f.getAtaque()});
         }
    
    
    }
    public void LimparCampos(){
    
               txtNfNome.setText("");
               txtNfFor.setText("");
               txtNfCon.setText("");
               txtNfDes.setText("");
               txtNfInt.setText("");
               txtNfSab.setText("");
               txtNfCar.setText("");
               txtNfPv.setText("");
               txtNfCa.setText("");
               txtNfAtk.setText("");     
               cbTipo.setSelectedItem(0);

    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNfNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNfAtk = new javax.swing.JTextField();
        txtNfCa = new javax.swing.JTextField();
        txtNfPv = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNfFor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNfCon = new javax.swing.JTextField();
        txtNfDes = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNfInt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNfSab = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNfCar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        cbTipo = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtFichas = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Criação de ficha");
        setResizable(false);

        jLabel1.setText("Nome:");

        jLabel2.setText("PV:");

        jLabel3.setText("CA:");

        jLabel4.setText("ATK:");

        jLabel5.setText("FOR:");

        jLabel6.setText("CON:");

        jLabel7.setText("DES:");

        jLabel8.setText("INT:");

        jLabel9.setText("SAB:");

        jLabel10.setText("CAR:");

        jLabel11.setText("Tipo de ficha:");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum Tipo", "Personagem", "NPC" }));
        cbTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTipoItemStateChanged(evt);
            }
        });
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });

        jtFichas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "TIPO", "PV", "CA", "ATK"
            }
        ));
        jtFichas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtFichasMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtFichasMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtFichasMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jtFichas);
        if (jtFichas.getColumnModel().getColumnCount() > 0) {
            jtFichas.getColumnModel().getColumn(0).setResizable(false);
            jtFichas.getColumnModel().getColumn(5).setResizable(false);
        }

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 590, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNfNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNfFor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtNfCar)
                                            .addComponent(txtNfSab, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNfInt, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNfDes, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNfCon, javax.swing.GroupLayout.Alignment.LEADING))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNfPv, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                    .addComponent(txtNfCa)
                                    .addComponent(txtNfAtk))))
                        .addGap(469, 469, 469)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNfFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNfCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNfDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNfPv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNfCa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNfAtk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNfInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNfSab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNfCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir)
                    .addComponent(btnLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        if(!sv.IsCampoVazio(txtNfNome.getText())&&!sv.IsCampoVazio(txtNfFor.getText())&&!sv.IsCampoVazio(txtNfCon.getText())&&!sv.IsCampoVazio(txtNfDes.getText())&&!sv.IsCampoVazio(txtNfInt.getText())
                &&!sv.IsCampoVazio(txtNfSab.getText())&&!sv.IsCampoVazio(txtNfCar.getText())&&!sv.IsCampoVazio(txtNfPv.getText())&&!sv.IsCampoVazio(txtNfCa.getText())
                &&!sv.IsCampoVazio(txtNfAtk.getText())&&cbTipo.getSelectedIndex()!=0){
            
           sv.TratarDadosFicha(txtNfNome.getText(), txtNfFor.getText(), txtNfCon.getText(), txtNfDes.getText(), txtNfInt.getText(), txtNfSab.getText(), txtNfCar.getText(), txtNfPv.getText(), txtNfCa.getText(), txtNfAtk.getText(), cbTipo.getSelectedIndex());
          ReadLista();
          LimparCampos();
      
        }else{
             JOptionPane.showMessageDialog(null, "Campos invalidos");
        }
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoActionPerformed

    private void cbTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTipoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoItemStateChanged

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
      
        BancoDadosFichas bd = new BancoDadosFichas();
      
        Ficha fichaAtualizada= new Ficha();
      
            if(jtFichas.getSelectedRow()!=-1){
             fichaAtualizada.setNome(txtNfNome.getText());
              fichaAtualizada.setTipoFicha((String) cbTipo.getSelectedItem());
              fichaAtualizada.setForca(txtNfFor.getText());
              fichaAtualizada.setConstituicao(txtNfCon.getText());
              fichaAtualizada.setDestreza(txtNfDes.getText());
              fichaAtualizada.setInteligencia(txtNfInt.getText());
              fichaAtualizada.setSabedoria(txtNfSab.getText());
              fichaAtualizada.setCarisma(txtNfCar.getText());
              fichaAtualizada.setPv(txtNfPv.getText());
              fichaAtualizada.setCa(txtNfCa.getText());
              fichaAtualizada.setAtaque(txtNfAtk.getText());
              fichaAtualizada.setId((int) jtFichas.getValueAt(jtFichas.getSelectedRow(),0));
              
              
              bd.AtualizarFicha(fichaAtualizada);
              LimparCampos();
              ReadLista();
              JOptionPane.showMessageDialog(null, "Ficha Atualizada com sucesso!");
            
            }
             
      
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        BancoDadosFichas bd = new BancoDadosFichas();
        
        if(jtFichas.getSelectedRow()!=-1){
             bd.DeletaFicha((int) jtFichas.getValueAt(jtFichas.getSelectedRow(),0));
             LimparCampos();
             ReadLista();
             JOptionPane.showMessageDialog(null, "Ficha apagada com sucesso!");
              
        }
       
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jtFichasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtFichasMouseClicked
       DefaultTableModel df = (DefaultTableModel)jtFichas.getModel();
       ArrayList<Ficha> fichas = new ArrayList();
       fichas=BancoDadosFichas.ListaFichas();
       
       if(jtFichas.getSelectedRow()!=-1){
           int indice=(int) jtFichas.getValueAt(jtFichas.getSelectedRow(),0);
           for(Ficha f : fichas){              
               if(f.getId()==indice){
                   
               txtNfNome.setText(f.getNome());
               txtNfFor.setText(f.getForca());
               txtNfCon.setText(f.getConstituicao());
               txtNfDes.setText(f.getDestreza());
               txtNfInt.setText(f.getInteligencia());
               txtNfSab.setText(f.getSabedoria());
               txtNfCar.setText(f.getCarisma());
               txtNfPv.setText(f.getPv());
               txtNfCa.setText(f.getCa());
               txtNfAtk.setText(f.getAtaque());
               /*if(jtFichas.getValueAt(jtFichas.getSelectedRow(),2).equals("Personagem")){
                    cbTipo.setSelectedIndex(1);
               }else if(jtFichas.getValueAt(jtFichas.getSelectedRow(),2).equals("NPC")){
                    cbTipo.setSelectedIndex(2);
               }else{
                   cbTipo.setSelectedIndex(0);
               }
              */if(f.getTipoFicha().equals("")){
                  cbTipo.setSelectedItem(0);
              }
               cbTipo.setSelectedItem(f.getTipoFicha());
              
           
           }
          
        }
       }
    }//GEN-LAST:event_jtFichasMouseClicked

    private void jtFichasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtFichasMousePressed
      
        int a=0;
        
    }//GEN-LAST:event_jtFichasMousePressed

    private void jtFichasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtFichasMouseReleased
        
    }//GEN-LAST:event_jtFichasMouseReleased

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
      LimparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed
    
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriaFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriaFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriaFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriaFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriaFicha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jtFichas;
    private javax.swing.JTextField txtNfAtk;
    private javax.swing.JTextField txtNfCa;
    private javax.swing.JTextField txtNfCar;
    private javax.swing.JTextField txtNfCon;
    private javax.swing.JTextField txtNfDes;
    private javax.swing.JTextField txtNfFor;
    private javax.swing.JTextField txtNfInt;
    private javax.swing.JTextField txtNfNome;
    private javax.swing.JTextField txtNfPv;
    private javax.swing.JTextField txtNfSab;
    // End of variables declaration//GEN-END:variables
}
